### ISSUE TITLE
Add wp_body_open()

### ISSUE THREAD

**Issue by viktorix** [tradesouthwest/ClassicSixteen#3]
The theme should include `wp_body_open()`.
- https://developer.wordpress.org/reference/hooks/wp_body_open/
- https://www.wpeditorial.com/how-and-why-to-use-wp_body_open-when-creating-wordpress-themes/

This was backported in CP  v1.3.0 and will be included in v2.0.

**Comment by tradesouthwest** [comment]
https://github.com/tradesouthwest/ClassicSixteen/blob/7d2784dd4644bf688bb6017f0ffee34d10ca93e9/header.php#L24

**Comment by tradesouthwest** [comment]
Thanks for adding this. DONE.
